### PR TITLE
Remove top-level MCP enumeration

### LINKED ISSUE #52: MCP enum prevents using `MCP` package namespace in client code
**Describe the bug**

The `MCP` enum prevents explicitly referencing MCP types via the package namespace

**To Reproduce**

For example:

```
import MCP

class MyService {
   typealias Client = MCP.Client // does not work because MCP enum clashes with the package name
}
```

**Expected behavior**

Package types should not clash with the package namespace

### PR DESCRIPTION
**Pull request by mattt**
Follow-up to #44

Resolves #52 #51

### CODE REVIEW

File: Sources/MCP/Base/Error.swift [hunk 1]
```diff
@@ -246,3 +230,12 @@ extension MCPError: Hashable {
...
     }
 }
+
+// MARK: -
+
+/// This is provided to allow existing code that uses `MCP.Swift.Error` to continue
+/// to work without modification.
+///
+/// The MCPError type is now the recommended way to handle errors in MCP.
+@available(*, deprecated, renamed: "MCPError", message: "Use MCPError instead of MCP.Swift.Error")
```
Comment (mattt) [inline Sources/MCP/Base/Error.swift:240]:
```suggestion
@available(*, deprecated, renamed: "MCPError", message: "Use MCPError instead of MCP.Error")
```
